config/routes.rb
Rails.application.routes.draw do
  resources :todolists do
    resources :todo_items do
      member do
        patch:complete
      end
    end
  end
    # resources:todo_items
   
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "todolists#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todolist
  
end

app/models/todolist.rb
class Todolist < ApplicationRecord
    has_many :todo_items
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: %i[ show edit update destroy ]

  # GET /todolists or /todolists.json
  def index
    @todolists = Todolist.all
  end

  # GET /todolists/1 or /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists or /todolists.json
  def create
    @todolist = Todolist.new(todolist_params)

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to todolist_url(@todolist), notice: "Todolist was successfully created."}
        format.json { render :show, status: :created, location: @todolist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1 or /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to todolist_url(@todolist), notice: "Todolist was successfully updated." }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

 
  # DELETE /todolists/1 or /todolists/1.json
  def destroy
    @todolist.destroy

    respond_to do |format|
      format.html { redirect_to todolists_url, notice: "Todolist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = Todolist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todolist_params
      params.require(:todolist).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LISTs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/_form.html.erb
<%= form_with(model: todolist) do |form| %>
  <% if todolist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
        <% todolist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
    
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todolists/_todolist.html.erb
<div id="<%= dom_id todolist %>">
  <p>
    <strong>Title:</strong>
    <%= todolist.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= todolist.description %>
  </p>

</div>

app/views/todolists/edit.html.erb
<h1>Editing todolist</h1>

<%= render "form", todolist: @todolist %>

<br>

<div>
  <%= link_to "Show this todolist", @todolist %> |
  <%= link_to "Back to todolists", todolists_path %>
</div>

app/views/todolists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todolists</h1>

<div id="todolists">
  <% @todolists.each do |todolist| %>
    <%= render todolist %>
    <p>
      <%= link_to "Show this todolist", todolist %>
      <%= link_to button_to "Mark as completed", todolist %>
    </p>
  <% end %>
</div>

<%= link_to "New todolist", new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New todolist</h1>

<%= render "form", todolist: @todolist %>

<br>

<div>
  <%= link_to "Back to todolists", todolists_path %>
</div>

app/views/todolists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todolist %>

<div>
  <%= link_to "Edit this todolist", edit_todolist_path(@todolist) %> |
  <%= link_to "Back to todolists", todolists_path %>

  <%= button_to "Destroy this todolist", @todolist, method: :delete %>
</div>